remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Yuneidis Londoño Serna
submodulo: Nuevas Tecnologias
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/nuevas-tecnologias-2e440.appspot.com/o/Fotoyune.png?alt=media&token=4ee8cc69-822d-4036-8775-ae4f97c89f0f
